\documentclass[twocolumn, DIV24,a4paper,BCOR0mm]{scrartcl}
% \usepackage{kpfonts}

\usepackage[T1]{fontenc}

%Space around sections
\usepackage[compact]{titlesec}
\titlespacing{\section}{0pt}{2ex}{1ex}
\titlespacing{\subsection}{0pt}{1ex}{0ex}
\titlespacing{\subsubsection}{0pt}{-0.5ex}{-0.5ex}

%Paragraph spacing
\setlength{\parskip}{0cm}
\setlength{\parindent}{1em}

\linespread{0.9}
\usepackage{scrpage2}

\pagestyle{scrheadings}  
\setheadsepline{.4pt}
\ihead[]{Plotting cheat sheet}
\chead[]{}
\ohead[]{}
\ifoot[]{\textit{Dr Colin Gillespie - c.gillespie@ncl.ac.uk}}
\cfoot[]{}
\ofoot[\pagemark]{\pagemark}
<<setup, include=FALSE, cache=FALSE>>=
#options(replace.assign=TRUE,width=60)
opts_chunk$set(fig.path='figure/graphics-', cache.path='cache/graphics-', fig.align='center', fig.height=3)
#, dev='tikz', fig.width=5, fig.height=5, fig.show='hold', cache=TRUE, par=TRUE)
knit_hooks$set(crop=hook_pdfcrop)
  #par=function(before, options, envir){
#if (before && options$fig.show!='none') par(mar=c(4,4,.1,.1),cex.lab=.95,cex#.axis=.9,mgp=c(2,.7,0),tcl=-.3)
#}, crop=hook_pdfcrop)

@


\begin{document}
<<echo=FALSE>>=
ev = FALSE
@

\textsc{Work in progress}
\subsubsection*{Plotting}

<<eval=ev>>=
plot(x) # Basic scatter plot
plot(x, y) #Plot of x and y
hist(x) # Histogram
barplot(x) #Bar chart
boxplot(x) #Box and whiskers plot
pie(x) # Pie chart
@

\subsubsection*{Standard plot arguments}

<<eval=FALSE>>=
xlab = "x-axis label" #See also ylab
xlim = c(0, 10)#x axis range
main = "Main title"
sub = "sub title"
lwd = 2 #Line width
col = "red" #Line colour, or
col = 2 
@


\subsubsection*{Graphical parameters}

These can be set globally with \texttt{par(...)}; many can be passed as parameters to plotting commands.
\begin{itemize}
\item \texttt{adj} controls text justification: 0 left-justified, 0.5 centred, 1 right-justified.
\item \texttt{bg} specifies the colour of the background, e.g. \texttt{bg="red"} or \texttt{bg="blue"}. See \texttt{colors()} for a list of the 657 available colours. 
\item \texttt{bty} controls the type of box drawn around the plot, allowed values are: "o", "l", "7", "c", "u" ou "]" (the box looks like the corresponding character); if \texttt{bty="n"} the box is not drawn
\item \texttt{cex} a value controlling the size of texts and symbols with respect to the default. Related options are: \texttt{cex.axis}, \texttt{cex.lab}, \texttt{cex.main} and \texttt{cex.sub}.
\item \texttt{col} controls the color of symbols and lines; use color names: "red", "blue" see \texttt{colors()} or as "\#RRGGBB"; see rgb(), hsv(), gray(), and rainbow(); as for cex there are: col.axis, col.lab, col.main, col.sub
\item \texttt{font}: an integer which controls the style of text (1: normal, 2: italics, 3:bold, 4: bold italics); as for \texttt{cex} there are: \texttt{font.axis}, \texttt{font.lab}, \texttt{font.main}, \texttt{font.sub}
\item \texttt{las}: an integer which controls the orientation of the axis labels (0: parallel to the axes, 1: horizontal, 2: perpendicular to the axes, 3: vertical)
\end{itemize}
\newpage

<<echo=FALSE,fig.cap="R pch symbols",crop=TRUE, out.width='0.9\\linewidth',>>=
x = rep(1:13, 2)[1:26]
y = rep(1:2, each=13)[1:26]
plot(x, y, pch=0:25, bty="n", axes=FALSE, ylim=c(0.5,2.5), xlim=c(1, 13.5),
     xlab="", ylab="", cex=2)
text(x+0.3, y + 0.3, 0:25, cex=0.8)
@


\end{document}